### ISSUE TITLE
Modpack Submission

### ISSUE THREAD

**Issue by Darkmega18** [AstroInteractive/DiscordSuite#11]
G'day, I'd like to ask to register my pack into the mod. It's not big, and it's not released yet, but I'm working on it, and I've got a cover image and a title image that can be used for the picture.

The Pack is Called Dimension Divers.
Here is the backing image I use in technic Launcher with logo on it, and without if it should be fine without the logo in the corner.
![dimension divers base picture](https://user-images.githubusercontent.com/8104689/34259227-90a813ba-e6b5-11e7-8a0e-a833a6f50462.png)
![merged picture and logo](https://user-images.githubusercontent.com/8104689/34259228-90d61670-e6b5-11e7-8388-760bd612eb58.png)

**Comment by TheCodedOne** [comment]
Sorry but we're only supporting released packs or packs that are just about to release. and at the moment we only support curse modpacks

**Comment by Darkmega18** [comment]
Rip in pieces. thats either by choice or it's not an easy thing to add support due to some other complications...
So even if I'm closer to release I can't get it put on cause of technic pack...?
Is there a way you can implement a way through something like resource loader or resource packs or configs to allow unsupported packs that aren't built in to do it themselves? Cause I would like a way for it to atleast display a different name than just "minecraft" in an attempt to get people who see me on discord to wonder what that is specifically.

**Comment by TheCodedOne** [comment]
its by choice, I dont have a lot of time and keeping track of more than 1 modpack service is a lot of effort, and configs i have chosen not to do because it defeats the entire purpose of the modpack system with the icons

**Comment by Darkmega18** [comment]
Very well, understood. Atleast it shows I've got minecraft of some kind going, atleast I've got that.
