### ISSUE TITLE
Add localizations

### ISSUE THREAD

**Issue by PixelmonPRO** [AstroInteractive/DiscordSuite#12]
Hello! I play in Russia, and I would like to add Russian names that can be added through the config.
I would also like to know if I am the owner of my server, and I have my own client for the game. How could I add my image?

**Comment by Nik-mmzd** [comment]
+1, it'll be great to customize texts, images, modpack logo and name using config (don't kill me if I missed smth (= )

**Comment by PixelmonPRO** [comment]
@TheCodedOne ?

**Comment by TheCodedOne** [comment]
semi duplicate of #9, Usually modpacks dont have a different name for other languages so making the modpack show for every language would be kinda incorrect and a load of effort.
