### ISSUE TITLE
Modpack Submission

### ISSUE THREAD

**Issue by PixelmonPRO** [AstroInteractive/DiscordSuite#14]
Name: Pixelmon.PRO
Icon: 
![logo2](https://user-images.githubusercontent.com/26658563/34501668-09eeba48-f021-11e7-8c45-325b97d4e66e.png)

**Comment by TheCodedOne** [comment]
Is this pack released?

**Comment by PixelmonPRO** [comment]
This pack is available in my launcher client for the game)
5500+ users playing for my client and use my modpack for game

**Comment by TheCodedOne** [comment]
Sorry but i'm only supporting curse modpacks at the moment, and as pixelmon is basically illegal, i dont want to get involved with it in any way

**Comment by PixelmonPRO** [comment]
And if I make a specially modpack for this, can you add it?
The players are playing - and not displayed, this is not good ...
