### ISSUE TITLE
Modpack Submission

### ISSUE THREAD

**Issue by Cocanuta** [AstroInteractive/DiscordSuite#16]
Hello there, I was wondering if my ModPack could be added, it's on curse already with a bunch of users. My Twitch Sub server all love this mod in the pack, so it'd be great to get the pack listed in there.

https://minecraft.curseforge.com/projects/snatchybuckles

**Comment by TheCodedOne** [comment]
You need to provide a logo with a minimum size of 512x512 and a display name

**Comment by Cocanuta** [comment]
Apologies for missing that information.

Logo: 
![logo](https://user-images.githubusercontent.com/959219/34669960-1e457924-f46c-11e7-976e-1f91604b03e8.png)

Display name: SnatchyBuckles

Thanks in advance.
