### ISSUE TITLE
Modpack Submission - RTTF

### ISSUE THREAD

**Issue by ixDarkLorD** [AstroInteractive/DiscordSuite#19]
Modpack Name: Road To The Future
Url: https://minecraft.curseforge.com/projects/road-to-the-future
Icon:
![r logo 512x512](https://user-images.githubusercontent.com/34784038/34809899-2095c2ee-f6a9-11e7-9055-e6bb04ea3939.png)

**Comment by ixDarkLorD** [comment]
3 Days?

**Comment by TheCodedOne** [comment]
Sorry I've been sick lately, i will get around to it soon

**Comment by ixDarkLorD** [comment]
?!

**Comment by TheCodedOne** [comment]
Sorry it took so long, your key is 85cc7651-a956-4626-9c32-3e398ad7a521
