### ISSUE TITLE
Modpack Submission

### ISSUE THREAD

**Issue by NillerMedDild** [AstroInteractive/DiscordSuite#2]
Hello!

I'd like to submit my modpacks for compatibility - What do you need?

https://minecraft.curseforge.com/projects/enigmatica2
https://minecraft.curseforge.com/projects/enigmatica2expert

**Comment by TheCodedOne** [comment]
I'd need an icon, minimum size of 512x512 and a display name

**Comment by NillerMedDild** [comment]
Display name, enigmatica2: "Enigmatica 2"
Picture
![logodiscord](https://user-images.githubusercontent.com/21295394/33981778-68624d74-e0ae-11e7-8545-d6d236fef792.png)

Display name, enigmatica2expert: "Enigmatica 2: Expert"
Picture
![logodiscordexpert](https://user-images.githubusercontent.com/21295394/33981780-692df6b8-e0ae-11e7-8049-d5cf5601371e.png)

**Comment by TheCodedOne** [comment]
Enigmatic 2: c2413123-3f8d-403b-a07d-3bf65ab3b45d
Enigmatic 2 Expert: febd8e7f-5238-4a61-a0cc-8de9da88da55

**Comment by NillerMedDild** [comment]
Thank you. This may be a stupid question, but what do I do with those IDs?

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by NillerMedDild** [comment]
The names are "Enigmatica" not "Enigmatic", could you edit them please? :)
