### ISSUE TITLE
Modpack submission

### ISSUE THREAD

**Issue by xbony2** [AstroInteractive/DiscordSuite#21]
Display name: King Kung
Icon:
![king kung](https://user-images.githubusercontent.com/5623501/34949474-2f89e770-f9de-11e7-9f72-472801d3204c.png)
(This is not currently released, but I hope to release it soon. Will be on CurseForge and will be legal and stuff. If desired I can share when done.)

**Comment by TheCodedOne** [comment]
key is ac583ad6-b325-4437-ba22-e00196d43140
