### ISSUE TITLE
Modpack picture submission 

### ISSUE THREAD

**Issue by abelj001** [AstroInteractive/DiscordSuite#22]
Hi there, i was just wondering if its at all possible to add a custom picture to a already existing "tweaked" modpack. Thought it would be a neat idea for peeps to be able to click on my name and essentially see a picture advert for my server! Not looking for all my players to have it, Just interested to see if its possible, thanks  Discord : Jamoir#8687  👍 Thanks

**Comment by TheCodedOne** [comment]
oh my fucking god, will people please start checking for duplicates in previous closed issues https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20 https://github.com/AstroInteractive/DiscordSuite/issues/20
