### ISSUE TITLE
DiscordSuite not working properly

### ISSUE THREAD

**Issue by Kaperios** [AstroInteractive/DiscordSuite#26]
**DiscordSuite version:** 1.3.1
**Forge version:** 14.23.2.2611

Rich Presence on Discord says that i'm in the Main Menu but i'm in the Overworld for around 1,5h.
![image](https://user-images.githubusercontent.com/17909958/36072648-6fae41de-0f23-11e8-9478-3da3a8d65eb1.png)
![image](https://user-images.githubusercontent.com/17909958/36072650-7420159e-0f23-11e8-9ac6-8c85e5fd758d.png)

**Comment by SDUBZ** [comment]
im getting the same even though set name in configs

**Comment by TheCodedOne** [comment]
what do you mean set name in configs? theres no config to set name

**Comment by SDUBZ** [comment]
You sure O_O

[DiscordSuite.cfg.txt](https://github.com/AstroInteractive/DiscordSuite/files/1842688/DiscordSuite.cfg.txt)

**Comment by TheCodedOne** [comment]
that modpack param isnt for the name, its a deprecated way for modpack authors to add their modpack uuid

**Comment by SDUBZ** [comment]
oh ok so how do i get my pack added to database then ? theers isnt much info on how to setup mod etc

**Comment by TheCodedOne** [comment]
as long as your pack is on curse, the latest discordsuite automatically detects the pack, other launchers arent supported at the moment
