### ISSUE TITLE
FTB Revelation Request

### ISSUE THREAD

**Issue by TNTUP** [AstroInteractive/DiscordSuite#27]
Hi, I found this mod in All the mods 3^^ and I'm asking if theres for FTB Revelation? 

Its on Curse/Twitch/FTB Legacy launchers. Do I need to give the modpack icon or you can do it by copying the image on curseforge website?

Looked in modpacks.json and I couldn't find Revelation :(

Modpack url is https://www.feed-the-beast.com/projects/ftb-revelation

Also there's no template, sorry if theres missing details :X

**Comment by TheCodedOne** [comment]
Sorry but one of the modpack authors must request/authorise this request, until that happens this wont happen

**Comment by TNTUP** [comment]
Oh wow such a shame from your part... Thanks again

**Comment by TheCodedOne** [comment]
not my fault that i cant magically decide which modpack people are playing
