### ISSUE TITLE
Modpack Submissions - FTB SF3, Direwolf20 1.12

### ISSUE THREAD

**Issue by Mike5357** [AstroInteractive/DiscordSuite#29]
I'd like to request two official FTB packs be added:

Sky Factory 3: https://www.curseforge.com/minecraft/modpacks/ftb-presents-skyfactory-3
Direwolf20 1.12: https://www.curseforge.com/minecraft/modpacks/ftb-presents-direwolf20-1-12

Resized images:
![dw20](https://user-images.githubusercontent.com/12630858/36401899-9be8afce-15a8-11e8-805b-476c93eaa966.png)
![sf3](https://user-images.githubusercontent.com/12630858/36401900-9bf57f24-15a8-11e8-9f27-e75b94759906.png)

**Comment by TheCodedOne** [comment]
read #27
