### ISSUE TITLE
Pinging...

### ISSUE THREAD

**Issue by jacket430** [AstroInteractive/DiscordSuite#3]
Hey there. Running DiscordSuite-1.1.0 on my custom 1.12.2 server. On single-player everything is fine, shows up exactly like in the pictures on the page. But when I join my multiplayer server, the discord status says "Pinging..." between the dimension and elapsed time. Not sure if this is a bug or intentional. 

Not sure what other information you'd need but can supply logs if necessary.

**Comment by TheCodedOne** [comment]
This seems to happen randomly, i've managed to improve it in my dev env but its still patchy

**Comment by TheCodedOne** [comment]
closing this issue as 1.1.4 removes server MOTD support while i try to fix this without the crashes messing people up
