### ISSUE TITLE
Modpack Submission - Grand Voyage

### ISSUE THREAD

**Issue by MrHipsterG** [AstroInteractive/DiscordSuite#30]
Display name: Grand Voyage
Image: 
![grand_voyage_icon](https://user-images.githubusercontent.com/26767833/37257175-c0feb1ce-2565-11e8-9d0e-65681e723481.png)
Thank you for making this mod :)

**Comment by TheCodedOne** [comment]
i require the curse pack link now due to the 4.x update

**Comment by MrHipsterG** [comment]
https://minecraft.curseforge.com/projects/grand-voyage

**Comment by TheCodedOne** [comment]
added, give 5-10 minutes to sync up but loading up your pack should now have the integration

**Comment by MrHipsterG** [comment]
Not sure if this is normal but the pack is showing up as "Minecraft Enhanced 1.12.2" and doesn't have an icon.
