### ISSUE TITLE
Mod Requests, Aether Legacy, Aether II, and Glacidus

### ISSUE THREAD

**Issue by Lachney** [AstroInteractive/DiscordSuite#32]
Hi there, I help maintain the Aether Legacy mod and am an author for the in the works Glacidus mod.  I'd love to have the rich presence support for our mods including the lovely Aether II mod? Thanks! :)

https://minecraft.curseforge.com/projects/aether-legacy
https://minecraft.curseforge.com/projects/the-aether-ii
https://minecraft.curseforge.com/projects/glacidus

Display Names:
For Aether Legacy, perhaps you can make it say, "In the Aether of the past" since Aether Legacy is a port of the original Aether mod

For Aether II, you can make it say "In the Aether"

For Glacidus, is it possible to make it say, "On Glacidus" since the goal is that it's another planet? If not, just make it say, "In Glacidus"

Images:
![Glacidus](https://i.xjon.me/sCTgpV.png)
![AetherII](https://i.xjon.me/7Wv3Xb.png)
![AetherLegacy](https://i.xjon.me/7KFfpi.png)

**Comment by TheCodedOne** [comment]
Implemented in dev, will push an update for it sometime today

**Comment by CDAGaming** [comment]
@TheCodedOne There is currently no icon for the Aether II, any fix?
