### ISSUE TITLE
Crash when trying to launch modded Minecraft with this mod without an internet connection

### ISSUE THREAD

**Issue by vpontin** [AstroInteractive/DiscordSuite#33]
Exacly what says in title.

MC 1.12.2
Forge b2673
DiscordSuite-2.1.0.jar

If i try to launch Minecraft with this mod installed but without an internet connection, i got this crash:
https://gist.github.com/vpontin/37ea119725882a4424ff2967f21ee4f1

Occasionally discover this issue because i will be without internet for a few days, and i can only use mobile data for urgent issues.

**Comment by nicobasile** [comment]
I am having the same issue, although I have internet connection. The pack I was using it ATM3 5.9.4

https://gist.github.com/nicobasile/453c97bf481dd4daf30f9830a1dd3fe7

**Comment by TheCodedOne** [comment]
Fixed in 2.2.0
