### ISSUE TITLE
Modpack Submission AMod

### ISSUE THREAD

**Issue by nacjm** [AstroInteractive/DiscordSuite#39]
Display name: Aetherion Modpack
Image:
![menu](https://user-images.githubusercontent.com/7560033/39952112-6aaea248-554e-11e8-9b16-c6ae7d3983e8.png)
It's a mcupdater modpack because twitch launcher was causing hassles for some admins.

**Comment by TheCodedOne** [comment]
Currently DS only accepts curse packs
