### ISSUE TITLE
Modpack Submissions:

### ISSUE THREAD

**Issue by GeoRCCraft** [AstroInteractive/DiscordSuite#40]
Hey Coded, would you mind adding my packs, 
- Caved IN
- Caved IN Lite
- Pastoral
- Alone

Thank you :)
- GeoRCCraft

**Comment by GeoRCCraft** [comment]
These packs have still not been added. All of these are ATLauncher packs :)

**Comment by TheCodedOne** [comment]
Oh, thats why i cant find them, only curse packs are supported at the moment
