### ISSUE TITLE
Crash: loading pack from curse

### ISSUE THREAD

**Issue by danielm59** [AstroInteractive/DiscordSuite#41]
Crash on loading the Herdcraft 2 pack which has an icon registered.
https://pastebin.com/08pCtqYm

**Comment by danielm59** [comment]
Note this was in version 1.11 of the pack, I downgraded the mod in 1.11.1

**Comment by Zeitheron** [comment]
Confirmed with my pack, same stack trace.

**Comment by TheCodedOne** [comment]
Fix uploaded to curse

**Comment by Zeitheron** [comment]
Thank you ^.w.^
