### ISSUE TITLE
Modpack Submission - Nexus Advanced

### ISSUE THREAD

**Issue by Scravey** [AstroInteractive/DiscordSuite#43]
Display Name: Nexus Advanced
![image](https://user-images.githubusercontent.com/8934961/40893688-ecd13ab6-6768-11e8-9de2-7fafd52eb049.png)

Technic Link: https://www.technicpack.net/modpack/nexus-advanced-modpack.381101

Currently doing a large overhaul and update to my ancient pack, and would love for this to be included.

**Comment by TheCodedOne** [comment]
technic packs are not supported
