### ISSUE TITLE
[Suggestion] Allow users to use their own client.

### ISSUE THREAD

**Issue by FireController1847** [AstroInteractive/DiscordSuite#44]
It's be awesome if you could allow users to use their own Discord application with the mod. That way, if we want to add our modpack or just customize the images, you don't have to constantly add to your application. It'd also probably work better to make this work more like an 'API' rather than being locked to one image set :)

**Comment by FireController1847** [comment]
Won't fix? Does that meant the suggestion is rejected or..m?

**Comment by TheCodedOne** [comment]
there are limitations and general legalities preventing this, its rejected cause it cant happen

**Comment by FireController1847** [comment]
Limitations? Legalities? Of course there will be limitations, it's not using a verified/accepted app, but users should understand that. This is for modpack creators who don't want to have to ask you to add their images to the thing, or maybe even for those who just want to put a simple private pack together.

The only "limitations" I can think of are inviting other users to play with you. There should be no limitions in that Discord Rich Presence uses a client ID, and then uses images from that client. As long as the user uploads the images with the same name, they can easily set up their own rich presence still using your mod.

Legalities? Really? ANYONE can do rich presence. Hell, I even made the mod pretty quickly and simply. What "legalities" are you talking about?
