### ISSUE TITLE
[Question] Link to Discord/Contact Info?

### ISSUE THREAD

**Issue by FireController1847** [AstroInteractive/DiscordSuite#45]
I don't know if you remember me, but I made [this project](https://github.com/FireController1847/Minecraft-DRP) a while back when you guys spoke to me on Discord. Now it seems I've lost your contact on Discord 😅 . So I went searching around but there doesn't seem to be any contact info for you guys! I'd love to help develop the mod as I want to get back into it, so please, I'd love to chat it up with you guys.

Here's my contact info, in case you want to do that first.
- Email: `contact@visualfiredev.com`
- Discord: `FireController1847#3577`
- Twitter: `@FireControl1847`

**Comment by TheCodedOne** [comment]
https://discord.gg/758eCD7
