### ISSUE TITLE
Modpack Submission - GameCraft Remastered

### ISSUE THREAD

**Issue by ItsDizzy** [AstroInteractive/DiscordSuite#49]
Modpack Name: GameCraft Remastered
Url: https://minecraft.curseforge.com/projects/gamecraft-remastered
Icon: 
![636525970383592515](https://user-images.githubusercontent.com/20015650/41784600-7aee80ca-7640-11e8-8fa0-a4c7a75aad1e.png)
(might change in the future)

**Comment by TheCodedOne** [comment]
The pack linked does not use discordsuite, image integration is limited to packs that include discordsuite due to the limited amount of images i am allowed to use.
