### ISSUE TITLE
Crash in preInit ( ModpackHandler.getModpack() ) on new installation

### ISSUE THREAD

**Issue by deregges** [AstroInteractive/DiscordSuite#51]
Complete crash report: https://pastebin.com/mtS0Qrsg
Configs are untouched.

After looking a bit into the code I personally suspect
`DiscordSuite.CURSE_MANIFEST.projectID != 0`
with projectID being null.

**Comment by TheCodedOne** [comment]
Duplicate of #41

**Comment by TheCodedOne** [comment]
And please, dont decompile the mod.. the licence forbids it
