### ISSUE TITLE
Modpack Request: CUBG or CrayfishUnknown's Battlegrounds

### ISSUE THREAD

**Issue by JacksonPlayz** [AstroInteractive/DiscordSuite#52]
Image:
![cubg](https://user-images.githubusercontent.com/18062275/42008737-eb1f4484-7a3b-11e8-83f1-12c46772b751.png)

Curseforge Page: https://minecraft.curseforge.com/projects/cubg

Project ID: 290803
Mar 24, 2018

**Comment by TheCodedOne** [comment]
The pack linked does not use discordsuite, image integration is limited to packs that include discordsuite due to the limited amount of images i am allowed to use.

**Comment by JacksonPlayz** [comment]
I've already added DiscordSuite for the next update. I'm just waiting for this to be added so I don't have to push two updates to the pack.
