### ISSUE TITLE
Show amount of mods loaded if modpack isn't supported

### ISSUE THREAD

**Issue by DoctorNefario** [AstroInteractive/DiscordSuite#57]
The ability to change what it says using the config file would also be a nice addition.

**Comment by TheCodedOne** [comment]
All modpacks are supported name-wise at the moment, plus i really hate the idea of comparing modpacks based on the amount of mods

**Comment by DoctorNefario** [comment]
I understand not wanting to compare modpacks by the amount of mods, it doesn't indicate quality in the slightest. However, I stand by my suggestion to be able to change the Rich Presence text in the config file.

Sometimes people want to use DiscordSuite for something that isn't even a modpack, like I do.
At least something to indicate that it's not vanilla Minecraft
