### ISSUE TITLE
Formatting codes in server's MOTD parses incorrectly

### ISSUE THREAD

**Issue by fixator10** [AstroInteractive/DiscordSuite#6]
So, what title says:
[Formatting codes](https://minecraft.gamepedia.com/Formatting_codes) in server's MOTD parses incorrectly

Server with MOTD `§1R§2e§3d§4s§5t§6o§7n§8e §9C§ar§be§ca§dt§ei§fo§1n§2s` shows as `�1R�2e�3d�4s�5t�6o�7n�8e �9C�ar�be�ca�dt�ei�fo�1n�2s�r` in discord rich presence:
![Server](https://Moeka.is-a-good-waifu.com/d5c20a.png)
![Discord](https://Moeka.is-a-good-waifu.com/6895cf.png)

**Comment by TheCodedOne** [comment]
Hrm.. this shouldn't happen im not sure why it does

**Comment by fixator10** [comment]
Installed modloaders:
![MMC5 Version](https://Moeka.is-a-good-waifu.com/a6a15a.png)
Installed mods:
![MMC5 Mods](https://Moeka.is-a-good-waifu.com/a632d8.png)

Launcher: MultiMC5 develop-1138

**Comment by fixator10** [comment]
Looks like there is problem with unicode. (UTF-8?)

**English**
![English](https://Moeka.is-a-good-waifu.com/f539b3.png)
**Japaneese** 
![Japaneese](https://Moeka.is-a-good-waifu.com/9be15d.png)
**Russian**
![Russian](https://Moeka.is-a-good-waifu.com/6cb926.png)

Also:
**English, HyPixel, Formatting codes in MOTD**
![Server's MOTD](https://Moeka.is-a-good-waifu.com/461070.png)
![English, HyPixel, Formatting codes in MOTD](https://Moeka.is-a-good-waifu.com/229ad7.png)

**Comment by TheCodedOne** [comment]
not sure why hypixel is wrong too, i tested with hypixel and there were no erroors

**Comment by fixator10** [comment]
Launching game forcely with UTF8 encoding (`-Dfile.encoding=UTF8` in MC launch parameters) fixes it, but this should be fixed via mod itself, i think.
Also text formatting (control character-paragraph+hex digits) shouldn't appear in rich presence, IMHO
![UTF8 fixed](https://Moeka.is-a-good-waifu.com/00d65f.png)

**Comment by TheCodedOne** [comment]
hm.. they shouldn't appear, i have them filtered out

**Comment by TheCodedOne** [comment]
which version of the mod are you on?

**Comment by fixator10** [comment]
`DiscordSuite-1.1.1.jar`
MC 1.12.2
`ForgeVersion=14.23.0.2529`

**Comment by TheCodedOne** [comment]
can you try DS 1.1.2

**Comment by fixator10** [comment]
Nothing seems to be changed.
Without `-Dfile.encoding=UTF8` encoding is incorrect
With it, control characters is displayed, but now rich presence also shows second line of MOTD
![UTF8, HyPixel](https://Moeka.is-a-good-waifu.com/dce11d.png)

**Comment by TheCodedOne** [comment]
closing this issue as 1.1.4 removes server MOTD support while i try to fix this without the crashes messing people up
