### ISSUE TITLE
Modpack submission

### ISSUE THREAD

**Issue by xbony2** [AstroInteractive/DiscordSuite#7]
Name: [WikiPack 3](https://minecraft.curseforge.com/projects/wikipack-3)

Icon:
![wikipack 3 logo](https://user-images.githubusercontent.com/5623501/34114110-d9ec3fd4-e3df-11e7-9d95-f03945bb8440.png)

Thanks ^^

**Comment by TheCodedOne** [comment]
f70dab8d-d8f3-4fa1-9011-f228a148c602
