### ISSUE TITLE
Modpack Submission

### ISSUE THREAD

**Issue by TronDev** [AstroInteractive/DiscordSuite#8]
Name: [All the Mods 3](https://minecraft.curseforge.com/projects/all-the-mods-3)

Icon: 
![image](https://user-images.githubusercontent.com/7727003/34174232-40a72ae0-e4c6-11e7-8015-1b39ae1f4b5f.png)

**Comment by OrdinatorStouff** [comment]
as an official ATM team member, I support this being added.

I will double-check/confirm the image (and provide higher resolution) soon.
