### ISSUE TITLE
[Feature Request] Config option for custom modpacks

### ISSUE THREAD

**Issue by Xiaminou** [AstroInteractive/DiscordSuite#9]
How about adding something in the config file where you can enter the name of your modpack you want to appear in Discord? It would make it easier to integrate new modpacks, all modpack authors would have to do is change that line the config. And for people who haven't made their modpack public they would still be able to display it on Discord.

**Comment by TheCodedOne** [comment]
The reason this hasn't been done is you cannot show a custom icon, and we're only supporting public packs

**Comment by Xiaminou** [comment]
Well I wasn't talking about changing the icon, but okay...

**Comment by Excaliburns** [comment]
Why not just attach the default icon to a custom name? Is that not possible?
